// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutreachStudio.Data;

#nullable disable

namespace OutreachStudio.Data.Migrations
{
    [DbContext(typeof(OutreachDbContext))]
    partial class OutreachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutreachStudio.Data.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reviewer");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_approvals_campaign_id");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AudienceSize")
                        .HasColumnType("integer")
                        .HasColumnName("audience_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.CampaignVersion", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channels");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_body");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_subject");

                    b.Property<double>("HoldoutShare")
                        .HasColumnType("double precision")
                        .HasColumnName("holdout_share");

                    b.Property<int>("PerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("per_minute");

                    b.Property<string>("PushBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("push_body");

                    b.Property<string>("PushTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("push_title");

                    b.Property<int>("QuietEndHour")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_end_hour");

                    b.Property<int>("QuietStartHour")
                        .HasColumnType("integer")
                        .HasColumnName("quiet_start_hour");

                    b.Property<string>("RuleJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rule_json");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.HasKey("CampaignId", "Number")
                        .HasName("pk_campaign_versions");

                    b.ToTable("campaign_versions", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.Delivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SkipReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skip_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("ProviderMessageId")
                        .HasDatabaseName("ix_deliveries_provider_message_id");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("ix_deliveries_campaign_id_status");

                    b.HasIndex("Status", "DueAt")
                        .HasDatabaseName("ix_deliveries_status_due_at");

                    b.HasIndex("UserId", "SentAt")
                        .HasDatabaseName("ix_deliveries_user_id_sent_at");

                    b.HasIndex("CampaignId", "UserId", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_deliveries_campaign_id_user_id_channel");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.DeliveryAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DeliveryId")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id")
                        .HasName("pk_delivery_attempts");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_delivery_attempts_started_at");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.Suppression", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Email")
                        .HasName("pk_suppressions");

                    b.ToTable("suppressions", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateOnly>("LastActive")
                        .HasColumnType("date")
                        .HasColumnName("last_active");

                    b.Property<bool>("MarketingConsent")
                        .HasColumnType("boolean")
                        .HasColumnName("marketing_consent");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("points_balance");

                    b.Property<DateOnly>("SignupDate")
                        .HasColumnType("date")
                        .HasColumnName("signup_date");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.UserEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_events");

                    b.HasIndex("UserId", "Type", "OccurredAt")
                        .HasDatabaseName("ix_user_events_user_id_type_occurred_at");

                    b.ToTable("user_events", (string)null);
                });

            modelBuilder.Entity("OutreachStudio.Data.Approval", b =>
                {
                    b.HasOne("OutreachStudio.Data.Campaign", null)
                        .WithMany("Approvals")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_campaigns_campaign_id");
                });

            modelBuilder.Entity("OutreachStudio.Data.CampaignVersion", b =>
                {
                    b.HasOne("OutreachStudio.Data.Campaign", null)
                        .WithMany("Versions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_versions_campaigns_campaign_id");
                });

            modelBuilder.Entity("OutreachStudio.Data.Campaign", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
