<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../OutreachStudio.Data/OutreachStudio.Data.csproj" />
    <ProjectReference Include="../OutreachStudio.ServiceDefaults/OutreachStudio.ServiceDefaults.csproj" />
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
